#!/bin/sh

set -e

lb config noauto \
  --bootappend-live "boot=live components persistence" \
  --architectures i386 \
  --mode debian \
  --distribution jessie \
  --archive-areas "main contrib non-free" \
  "${@}"
